### ISSUE TITLE
api_key & Api_url

### ISSUE THREAD

**Issue by ViPeR5000** [V0r-T3x/pwnagotchi_plugins#1]
How to Define

api_key & Api_url

**Comment by V0r-T3x** [comment]
to get the api_key for wpa-sec go there: https://wpa-sec.stanev.org/?get_key

inside the /etc/pwnagotchi/config.toml:
```
main.plugins.wpa-sec.enabled = true
main.plugins.wpa-sec.api_key = "your generated api_key here"
main.plugins.wpa-sec.api_url = "https://wpa-sec.stanev.org"
main.plugins.wpa-sec.download_results = true
main.plugins.wpa-sec.whitelist = []
```

**Comment by ViPeR5000** [comment]
its the api key to banthex is missing
```

main.plugins.crack_house.api_key = ""
main.plugins.crack_house.api_url = "https://banthex.de/"

```

**Comment by ViPeR5000** [comment]
BANTHEX: API-KEY isn't set. Can't upload to banthex.de

**Comment by V0r-T3x** [comment]
to get the api_key for banthed go there: https://banthex.de/index.php/register/
create an account, connect to the site and go there: https://banthex.de/index.php/wpa-psk-auditor/
you will be able to generate an api_key as wpa-sec
the plugin and the banthex backend code are clones of wpa-sec to run both on the same pwnagotchi

```
main.plugins.banthex.enabled = true
main.plugins.banthex.api_key = "your gnerated api_key here"
main.plugins.banthex.api_url = "https://banthex.de/wpa/"
main.plugins.banthex.download_results = true
main.plugins.banthex.whitelist = []
```

banthex is a recent site (by [@banthex](https://github.com/Banthex)), you can help to crack password too. The site have a leaderboard of the members.
https://github.com/Banthex/help_crack_banthex

**Comment by ViPeR5000** [comment]
thks
